[project]
name = "slackbot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "fastapi[standard]>=0.116.1",
    "openai>=1.0.0",
    "requests>=2.32.5",
    "slack-sdk>=3.27.0",
]
